[build]
  # Utilise un script personnalisé pour installer Flutter et builder le projet
  command = "bash build.sh"
  # Dossier contenant le résultat du build
  publish = "build/web"

# Redirection obligatoire pour Flutter Web (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
